### ISSUE TITLE
Mispellings in Brazilian Portuguese

### ISSUE THREAD

**Issue by gmoliveira** [frappe/translator#182]
is https://translate.erpnext.com/ working? I tried to send some translations, but its not showing on the site.
Nevertheless i'd like to contribute with Brazilian Portuguese translations, since there are still many texts to be translated and some minor corrections.

Thanks a lot for your effort.
Gustavo

**Comment by sahil28297** [comment]
Yes, https://translate.erpnext.com is working fine, the website only shows first 100 translations, in order to view all translations, try signing up on https://translate.erpnext.com. You will also become a verifier and can change the status of contributed translations to "Verified" for your native translations that you feel is correct.

Cheers.
